name: Publish

env:
  AZURE_WEBAPP_PACKAGE_PATH: "./myapp"
  ARTIFACT_NAME: "Slimsy.Web-v"
  FRONTEND_ARTIFACT_NAME: "Slimsy.Frontend-v"
  DOTNET_VERSION: '8'                 # set this to the .NET Core version to use
  PATH_TO_CSPROJ: "src/Slimsy.TestSite"
  CSPROJ_NAME: "Slimsy.TestSite.csproj"
  GH_TOKEN: ${{ github.token }}

on:
  workflow_dispatch:

jobs:
  setup:
    name: Setup our build
    runs-on: ubuntu-latest
    outputs:
      semver: ${{ env.RELEASE_VERSION }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Tag Version
        run: echo "RELEASE_VERSION=$(git describe --tags --abbrev=0 main-v6)" >> $GITHUB_ENV
      - name: Echo Release Version
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
